#!/bin/zsh

FILE_ORIGINAL=$1
FILENAME=$2
FFMPEG_ARGS="-vn -acodec aac -b:a 320k"

if [ -z "$FILE_ORIGINAL" ]
then
	echo "You need to pass a file as the first arg"
	exit 1
else
	if [ -z "$FILENAME" ]
	then
		ffmpeg -i "$FILE_ORIGINAL" $FFMPEG_ARGS "${FILE_ORIGINAL%.*}.m4a"
	else
		ffmpeg -i "$FILE_ORIGINAL" $FFMPEG_ARGS "${FILE_ORIGINAL%/*.*}/${FILENAME%.*}.m4a"
	fi
fi