#!/bin/zsh

FFMPEG_ARGS="-vcodec h264 -acodec aac -strict -2 -crf 18 -preset slow"
H265=false

while test $# -gt 0; do
  case "$1" in
    -h|--h265)
      shift
      H265=true
      break
      ;;
      *)
      break
      ;;
  esac
done

FILE_ORIGINAL=$1
FILENAME=$2

if $H265
then
  FFMPEG_ARGS="-vcodec libx265 -crf 28"
fi

if [ -z "$FILE_ORIGINAL" ]
then
	echo "You need to pass a video file as the first arg"
	exit 1
else
	if [ -z "$FILENAME" ]
	then
		ffmpeg -i "$FILE_ORIGINAL" $FFMPEG_ARGS "${FILE_ORIGINAL%.*}.mp4"
	else
		ffmpeg -i "$FILE_ORIGINAL" $FFMPEG_ARGS "${FILE_ORIGINAL%/*.*}/${FILENAME%.*}.mp4"
	fi
fi