#!/bin/bash

# Usage: pdf file.pdf
# --> extracts first page as file.jpg in the same directory
# --> specify the page number as the second argument if you wish

INPUT=$1
PAGE=1

re='^[0-9]+$'

if [ -n "$2" ]
then
    if [[ $2 =~ $re ]] ; then
        PAGE=$2
    fi
fi

pdftoppm -jpeg -f "$PAGE" -l "$PAGE" -singlefile "$INPUT" "${INPUT%.*}"