#!/bin/zsh

FILE_ORIGINAL=$1
FILENAME=$2
FFMPEG_ARGS=" -f wav -bitexact -acodec pcm_s16le -ar 22050 -ac 1 "

if [ -z "$FILE_ORIGINAL" ]
then
	echo "You need to pass a file as the first arg"
	exit 1
else
	if [ -z "$FILENAME" ]
	then
		ffmpeg -i "$FILE_ORIGINAL" $FFMPEG_ARGS "${FILE_ORIGINAL%.*}.wav"
	else
		ffmpeg -i "$FILE_ORIGINAL" $FFMPEG_ARGS "${FILE_ORIGINAL%/*.*}/${FILENAME%.*}.wav"
	fi
fi